import { filterUnusedQuestions } from "./question-history";
import { QuestionType, QuizCategory, type Question } from "./types";

export const fallbackQuestions: Record<QuizCategory, Question[]> = {
  [QuizCategory.GENERAL]: [
    {
      id: "fallback_general_1",
      text: "What is the chemical symbol for gold?",
      type: QuestionType.TEXT,
      options: null,
      correctAnswer: "Au",
      category: QuizCategory.GENERAL,
      explanation: "Au comes from the Latin word aurum.",
    },
    {
      id: "fallback_general_2",
      text: "Which planet is known as the Red Planet?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["Venus", "Mars", "Jupiter", "Saturn"],
      correctAnswer: "Mars",
      category: QuizCategory.GENERAL,
      explanation: "Mars appears red due to iron oxide on its surface.",
    },
    {
      id: "fallback_general_3",
      text: "In which year did the Titanic sink?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["1905", "1912", "1918", "1923"],
      correctAnswer: "1912",
      category: QuizCategory.GENERAL,
      explanation: "The Titanic sank on its maiden voyage in April 1912.",
    },
    {
      id: "fallback_general_4",
      text: "What is the largest organ in the human body?",
      type: QuestionType.TEXT,
      options: null,
      correctAnswer: "Skin",
      category: QuizCategory.GENERAL,
      explanation: "The skin accounts for roughly 16% of body weight.",
    },
    {
      id: "fallback_general_5",
      text: "Which language has the most native speakers worldwide?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["English", "Spanish", "Mandarin Chinese", "Hindi"],
      correctAnswer: "Mandarin Chinese",
      category: QuizCategory.GENERAL,
      explanation: "Mandarin has over 900 million native speakers.",
    },
    {
      id: "fallback_general_6",
      text: "How many continents are there?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["5", "6", "7", "8"],
      correctAnswer: "7",
      category: QuizCategory.GENERAL,
      explanation: "Africa, Antarctica, Asia, Europe, North America, Oceania, and South America.",
    },
    {
      id: "fallback_general_7",
      text: "What is the capital of Japan?",
      type: QuestionType.TEXT,
      options: null,
      correctAnswer: "Tokyo",
      category: QuizCategory.GENERAL,
      explanation: "Tokyo has been Japan's capital since 1868.",
    },
    {
      id: "fallback_general_8",
      text: "Which gas do plants absorb from the atmosphere?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"],
      correctAnswer: "Carbon dioxide",
      category: QuizCategory.GENERAL,
      explanation: "Plants use carbon dioxide during photosynthesis.",
    },
    {
      id: "fallback_general_9",
      text: "Who painted the Mona Lisa?",
      type: QuestionType.TEXT,
      options: null,
      correctAnswer: "Leonardo da Vinci",
      category: QuizCategory.GENERAL,
      explanation: "Leonardo da Vinci painted it in the early 1500s.",
    },
    {
      id: "fallback_general_10",
      text: "What is the smallest prime number?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["0", "1", "2", "3"],
      correctAnswer: "2",
      category: QuizCategory.GENERAL,
      explanation: "2 is the only even prime number.",
    },
  ],
  [QuizCategory.SPORT]: [
    {
      id: "fallback_sport_1",
      text: "How many players are on a football pitch for one team?",
      type: QuestionType.TEXT,
      options: null,
      correctAnswer: "11",
      category: QuizCategory.SPORT,
      explanation: "Each team fields 11 players including the goalkeeper.",
    },
    {
      id: "fallback_sport_2",
      text: "Which country has won the most FIFA World Cups?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["Germany", "Italy", "Brazil", "Argentina"],
      correctAnswer: "Brazil",
      category: QuizCategory.SPORT,
      explanation: "Brazil has won the World Cup five times.",
    },
    {
      id: "fallback_sport_3",
      text: "In tennis, what score comes after deuce?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["Game", "Advantage", "Set point", "Break"],
      correctAnswer: "Advantage",
      category: QuizCategory.SPORT,
      explanation: "A player must win two consecutive points after deuce.",
    },
    {
      id: "fallback_sport_4",
      text: "How many rings are on the Olympic flag?",
      type: QuestionType.TEXT,
      options: null,
      correctAnswer: "5",
      category: QuizCategory.SPORT,
      explanation: "The five rings represent the inhabited continents.",
    },
    {
      id: "fallback_sport_5",
      text: "Which sport uses a scrum?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["Cricket", "Rugby", "Hockey", "Basketball"],
      correctAnswer: "Rugby",
      category: QuizCategory.SPORT,
      explanation: "A scrum restarts play after certain infringements in rugby.",
    },
  ],
  [QuizCategory.MUSIC]: [
    {
      id: "fallback_music_1",
      text: "Who is known as the King of Pop?",
      type: QuestionType.TEXT,
      options: null,
      correctAnswer: "Michael Jackson",
      category: QuizCategory.MUSIC,
      explanation: "Michael Jackson earned the nickname throughout his career.",
    },
    {
      id: "fallback_music_2",
      text: "Which band released the album Abbey Road?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["The Rolling Stones", "The Beatles", "Queen", "Led Zeppelin"],
      correctAnswer: "The Beatles",
      category: QuizCategory.MUSIC,
      explanation: "Abbey Road was released in 1969.",
    },
    {
      id: "fallback_music_3",
      text: "How many strings does a standard violin have?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["4", "5", "6", "7"],
      correctAnswer: "4",
      category: QuizCategory.MUSIC,
      explanation: "A standard violin has four strings tuned in fifths.",
    },
    {
      id: "fallback_music_4",
      text: "Which artist had a 2020 hit with 'Blinding Lights'?",
      type: QuestionType.TEXT,
      options: null,
      correctAnswer: "The Weeknd",
      category: QuizCategory.MUSIC,
      explanation: "Blinding Lights topped charts in over 30 countries.",
    },
    {
      id: "fallback_music_5",
      text: "What instrument did Louis Armstrong primarily play?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["Saxophone", "Trumpet", "Piano", "Clarinet"],
      correctAnswer: "Trumpet",
      category: QuizCategory.MUSIC,
      explanation: "Armstrong was one of jazz's most influential trumpeters.",
    },
  ],
  [QuizCategory.FILM_TV]: [
    {
      id: "fallback_filmtv_1",
      text: "Who directed Jurassic Park?",
      type: QuestionType.TEXT,
      options: null,
      correctAnswer: "Steven Spielberg",
      category: QuizCategory.FILM_TV,
      explanation: "Spielberg directed the 1993 blockbuster.",
    },
    {
      id: "fallback_filmtv_2",
      text: "Which film won the Academy Award for Best Picture in 1995?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["Pulp Fiction", "Forrest Gump", "The Shawshank Redemption", "Speed"],
      correctAnswer: "Forrest Gump",
      category: QuizCategory.FILM_TV,
      explanation: "Forrest Gump won six Oscars including Best Picture.",
    },
    {
      id: "fallback_filmtv_3",
      text: "In Breaking Bad, what is Walter White's alias?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["The Chemist", "Heisenberg", "The Professor", "Blue Sky"],
      correctAnswer: "Heisenberg",
      category: QuizCategory.FILM_TV,
      explanation: "Heisenberg is inspired by the uncertainty principle.",
    },
    {
      id: "fallback_filmtv_4",
      text: "Which actor played Jack in Titanic?",
      type: QuestionType.TEXT,
      options: null,
      correctAnswer: "Leonardo DiCaprio",
      category: QuizCategory.FILM_TV,
      explanation: "DiCaprio starred alongside Kate Winslet in the 1997 film.",
    },
    {
      id: "fallback_filmtv_5",
      text: "What is the name of the fictional continent in Game of Thrones?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["Middle-earth", "Westeros", "Narnia", "Tamriel"],
      correctAnswer: "Westeros",
      category: QuizCategory.FILM_TV,
      explanation: "Most of the series takes place in Westeros.",
    },
  ],
  [QuizCategory.GEOGRAPHY]: [
    {
      id: "fallback_geography_1",
      text: "What is the capital of Japan?",
      type: QuestionType.TEXT,
      options: null,
      correctAnswer: "Tokyo",
      category: QuizCategory.GEOGRAPHY,
      explanation: "Tokyo has been Japan's capital since 1869.",
    },
    {
      id: "fallback_geography_2",
      text: "Which is the longest river in the world?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["Amazon", "Nile", "Yangtze", "Mississippi"],
      correctAnswer: "Nile",
      category: QuizCategory.GEOGRAPHY,
      explanation: "The Nile flows roughly 6,650 km through northeastern Africa.",
    },
    {
      id: "fallback_geography_3",
      text: "Which country has the most time zones?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["Russia", "USA", "France", "China"],
      correctAnswer: "France",
      category: QuizCategory.GEOGRAPHY,
      explanation: "France spans 12 time zones due to overseas territories.",
    },
    {
      id: "fallback_geography_4",
      text: "What is the smallest country in the world by area?",
      type: QuestionType.TEXT,
      options: null,
      correctAnswer: "Vatican City",
      category: QuizCategory.GEOGRAPHY,
      explanation: "Vatican City covers about 0.44 square kilometres.",
    },
    {
      id: "fallback_geography_5",
      text: "Mount Everest lies on the border of Nepal and which country?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["India", "China", "Bhutan", "Pakistan"],
      correctAnswer: "China",
      category: QuizCategory.GEOGRAPHY,
      explanation: "The summit straddles the Nepal–China border.",
    },
  ],
  [QuizCategory.GAMING]: [
    {
      id: "fallback_gaming_1",
      text: "What is the best-selling video game of all time?",
      type: QuestionType.TEXT,
      options: null,
      correctAnswer: "Minecraft",
      category: QuizCategory.GAMING,
      explanation: "Minecraft has sold over 300 million copies.",
    },
    {
      id: "fallback_gaming_2",
      text: "Which company makes the PlayStation console?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["Microsoft", "Nintendo", "Sony", "Sega"],
      correctAnswer: "Sony",
      category: QuizCategory.GAMING,
      explanation: "Sony launched the original PlayStation in 1994.",
    },
    {
      id: "fallback_gaming_3",
      text: "In The Legend of Zelda, what is the hero's name?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["Zelda", "Link", "Ganon", "Epona"],
      correctAnswer: "Link",
      category: QuizCategory.GAMING,
      explanation: "Link is the playable hero; Zelda is the princess.",
    },
    {
      id: "fallback_gaming_4",
      text: "Which year was the original Super Mario Bros. released?",
      type: QuestionType.TEXT,
      options: null,
      correctAnswer: "1985",
      category: QuizCategory.GAMING,
      explanation: "Super Mario Bros. launched for the NES in 1985.",
    },
    {
      id: "fallback_gaming_5",
      text: "What genre is the game Fortnite primarily known for?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["Racing", "Battle Royale", "Puzzle", "Simulation"],
      correctAnswer: "Battle Royale",
      category: QuizCategory.GAMING,
      explanation: "Fortnite popularised the battle royale format.",
    },
  ],
  [QuizCategory.HISTORY]: [
    {
      id: "fallback_history_1",
      text: "In which year did World War II end?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["1943", "1945", "1947", "1950"],
      correctAnswer: "1945",
      category: QuizCategory.HISTORY,
      explanation: "Germany surrendered in May 1945; Japan in September 1945.",
    },
    {
      id: "fallback_history_2",
      text: "Who was the first President of the United States?",
      type: QuestionType.TEXT,
      options: null,
      correctAnswer: "George Washington",
      category: QuizCategory.HISTORY,
      explanation: "Washington served from 1789 to 1797.",
    },
    {
      id: "fallback_history_3",
      text: "The Berlin Wall fell in which year?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["1987", "1989", "1991", "1993"],
      correctAnswer: "1989",
      category: QuizCategory.HISTORY,
      explanation: "The wall opened on 9 November 1989.",
    },
  ],
  [QuizCategory.SCIENCE]: [
    {
      id: "fallback_science_1",
      text: "What gas do plants absorb from the atmosphere?",
      type: QuestionType.TEXT,
      options: null,
      correctAnswer: "Carbon dioxide",
      category: QuizCategory.SCIENCE,
      explanation: "Plants use CO₂ in photosynthesis.",
    },
    {
      id: "fallback_science_2",
      text: "How many bones are in the adult human body?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["186", "206", "226", "246"],
      correctAnswer: "206",
      category: QuizCategory.SCIENCE,
      explanation: "Babies have more bones that fuse as they grow.",
    },
    {
      id: "fallback_science_3",
      text: "What is the speed of light in a vacuum (approx.)?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: [
        "300,000 km/s",
        "150,000 km/s",
        "30,000 km/s",
        "3,000 km/s",
      ],
      correctAnswer: "300,000 km/s",
      category: QuizCategory.SCIENCE,
      explanation: "Light travels at roughly 299,792 km/s.",
    },
  ],
  [QuizCategory.FOOD_DRINK]: [
    {
      id: "fallback_food_1",
      text: "Which country is the origin of champagne?",
      type: QuestionType.TEXT,
      options: null,
      correctAnswer: "France",
      category: QuizCategory.FOOD_DRINK,
      explanation: "Champagne comes from the Champagne region of France.",
    },
    {
      id: "fallback_food_2",
      text: "What spirit is the main ingredient in a Mojito?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["Vodka", "Rum", "Gin", "Tequila"],
      correctAnswer: "Rum",
      category: QuizCategory.FOOD_DRINK,
      explanation: "A classic Mojito uses white rum, lime, mint, and soda.",
    },
    {
      id: "fallback_food_3",
      text: "Sushi originated in which country?",
      type: QuestionType.TEXT,
      options: null,
      correctAnswer: "Japan",
      category: QuizCategory.FOOD_DRINK,
      explanation: "Modern sushi developed in Japan during the Edo period.",
    },
  ],
  [QuizCategory.POP_CULTURE]: [
    {
      id: "fallback_pop_1",
      text: "Which social media platform is known for short videos and dances?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: ["Twitter", "TikTok", "LinkedIn", "Reddit"],
      correctAnswer: "TikTok",
      category: QuizCategory.POP_CULTURE,
      explanation: "TikTok launched internationally in 2018.",
    },
    {
      id: "fallback_pop_2",
      text: "Who is known as the 'King of Pop'?",
      type: QuestionType.TEXT,
      options: null,
      correctAnswer: "Michael Jackson",
      category: QuizCategory.POP_CULTURE,
      explanation: "Michael Jackson earned the nickname over decades of hits.",
    },
    {
      id: "fallback_pop_3",
      text: "Which TV show features dragons and the Iron Throne?",
      type: QuestionType.MULTIPLE_CHOICE,
      options: [
        "The Witcher",
        "Game of Thrones",
        "Vikings",
        "The Crown",
      ],
      correctAnswer: "Game of Thrones",
      category: QuizCategory.POP_CULTURE,
      explanation: "Game of Thrones ran on HBO from 2011 to 2019.",
    },
  ],
};

function shuffleArray<T>(items: T[]): T[] {
  const shuffled = [...items];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

export function getFallbackQuestions(
  category: QuizCategory,
  count: number
): Question[] {
  const pool = fallbackQuestions[category];

  if (count > pool.length) {
    console.warn(
      `Requested ${count} fallback questions for ${category} but only ${pool.length} available`
    );
  }

  const shuffled = shuffleArray(pool);
  const unused = filterUnusedQuestions(shuffled);

  if (unused.length >= count) {
    return unused.slice(0, count);
  }

  // Reuse questions when the global history pool is exhausted.
  return shuffled.slice(0, count);
}
